Feature/message
BigBookMarket/BigBookMarket-Server pull request #27
Opened 2021-05-20 19:07 UTC by min0k0311

message 생성 기능 추가

2021-05-23 04:39 UTC, congcoding requested changes
리뷰해드린부분 #30 이랑 같이 참고해서 수정 부탁드려요~

2021-05-23 04:39 UTC, congcoding commented on src/main/java/com/bigbookmarket/web/dto/MessageBoxResponseDto.java
> +    private String userId;
nickname을 사용할거면 변수명을 nickname으로 해주세요. userId, id, nickname은 다음과 같습니다.

userId(Long) -> 자동으로 부여된 회원번호 (내부적으로 조인할 때 사용)
id(String) -> 로그인할 때 쓰는 id (클라이언트에서 특정 유저 정보 요청할 때 사용)
nickname(String) -> 실제 서비스에서 보여지는 nickname

2021-05-23 04:39 UTC, congcoding commented on src/main/java/com/bigbookmarket/web/UserController.java
> +    @GetMapping("/outbox/send/{id}")
/outbox/{id}로 하지 않고 send를 중간에 추가한 이유가 있나요? 특별한 이유가 없다면 둘이 맞춰주는게 좋을 것 같습니다!

2021-05-23 04:39 UTC, congcoding commented on src/main/java/com/bigbookmarket/web/dto/MessageResponseDto.java
> +    private User receiver;
#30 에서 언급한대로 이렇게하면 User의 pwd, phone 등 불필요한 정보까지 전달되니 내일 수정부탁드려요!

2021-05-24 05:40 UTC, min0k0311 commented
1번 빼고 다 수정했습니다! 2, 3번은 제가 값을 착각하고 1을 넣어서 오류가 생겼습니다! jbeen을 넣으니 잘 돌아갑니다! 감사합니다! 이제 1번 수정할게요

2021-05-24 06:47 UTC, merged