Buy, Comment, Item, Message 추가
BigBookMarket/BigBookMarket-Server pull request #9
Opened 2021-05-07 08:41 UTC by min0k0311

Buy, Comment, Item, Message 추가

2021-05-07 09:27 UTC, congcoding requested changes
고생하셨습니다!
수정 요청 부탁드린 부분들은 수정해서 다시 push 해주시고,
enum이나 변수명 등은 민영님이 하고 싶은대로 하세요~

2021-05-07 09:27 UTC, congcoding commented on src/main/java/com/bigbookmarket/domain/Buy.java
> +public class Buy extends BaseTimeEntity{
```suggestion
public class Buy extends BaseTimeEntity {
```

중괄호 { 앞에 스페이스 넣어주세요.

인텔리제이에서 저장키 누르면 자동으로 정렬되지 않나요?
저 원래 이런거 별로 신경 안 쓰는 사람인데 너무 특이하게 코딩하셔서 무슨 이유로 이렇게 하시는건지 궁금하네요...🧐

2021-05-07 09:27 UTC, congcoding commented on src/main/java/com/bigbookmarket/domain/Buy.java
> +
```suggestion
```

어노테이션이랑 클래스 사이에 개행 넣지 말아주세요.

2021-05-07 09:27 UTC, congcoding commented on src/main/java/com/bigbookmarket/domain/Item.java
> +    private Long price;
```suggestion
    private Integer price;
```

저희는 가격이니까 unsigned이긴 한데 signed Integer 최댓값 넘을 일 없을 것 같아서 그냥 Integer로 하는게 좋을 것 같아요~

2021-05-07 09:27 UTC, congcoding commented on src/main/java/com/bigbookmarket/domain/Item.java
> +    private Byte method;
주말에 시간 남으시면 enum으로 바꾸는거 시도해보시는 것도 좋을 것 같아요~
먼저 해주시면 그거 보고 저도 월요일에 하면 편하니까!
`jpa enum`으로 구글링하면 참고할만한 자료들이 많이 나오네요.

2021-05-07 09:27 UTC, congcoding commented on src/main/java/com/bigbookmarket/domain/Item.java
> +    private Byte status;
이 부분도 추후에 enum으로 바꿔야겠네요

2021-05-07 09:27 UTC, congcoding commented on src/main/java/com/bigbookmarket/domain/Message.java
> +    private User user2;
```suggestion
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "senderId", referencedColumnName = "userId")
    private User sender;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "receiverId", referencedColumnName = "userId")
    private User receiver;
```

이럴 때는 변수명을 sender or senderUser, receiver or receiverUser라고 하는게 안 헷갈리지 않을까요?
쪽지부분 구현은 민영님께 부탁드릴 예정인데 민영님께서 user, user2가 편하시면 이렇게 하셔도 됩니다~

2021-05-07 09:32 UTC, jwbeen commented on src/main/java/com/bigbookmarket/domain/Buy.java
> +public class Buy extends BaseTimeEntity{
```suggestion
public class Buy extends BaseTimeEntity {
```

어노테이션이랑 클래스 사이에 개행 넣지 말아주세요.
중괄호 { 앞에 스페이스 넣어주세요.

인텔리제이에서 저장키 누르면 자동으로 정렬되지 않나요?
저 원래 이런거 별로 신경 안 쓰는 사람인데 너무 특이하게 코딩하셔서 무슨 이유로 이렇게 하시는건지 궁금하네요...🧐

2021-05-10 05:58 UTC, congcoding requested changes
enum은 상수니까 대문자로 하는게 좋을 것 같아요!
ItemTradingMethod를 더 쉬운 방법으로 수정해봤는데 기존 코드로 하실거면 기존 코드로 하셔도 됩니다.
또, 테스트하기 힘드셨을 것 같아서 테스트코드를 추가해놨습니다!

2021-05-10 06:47 UTC, congcoding approved these changes
덕분에 enum을 더 효율적으로 사용하는 방법을 알 수 있었어요!
다음부터는 참고하신 링크를 보내주시면 제가 리뷰할 때 편할 것 같습니다!
https://tech.yangs.kr/16

2021-05-10 06:48 UTC, merged